### ISSUE TITLE
Setting Town Cost Item ID

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#112]
I'm unable to change the "S:costItem=diamond" to for example, the ID of a modded item such as GregTech Steel "S:costItem=5542:11305". Every time it reverts back to 'diamond'. Are you only able to put Vanilla items for the cost or is this a genuine bug? If it's not implemented, could this be added? It would be very useful to myself and many other server Owners. 

I'm running the following:
MyEssentials-Core-1.7.10-1.3-universal.jar
MyTown2-1.7.10-0.26a.jar
Forge: server-1.7.10-1263.jar

**Comment by AfterWind** [comment]
In Forge 1.7.10 there are no longer static item/block IDs therefore you need to ALWAYS use the unique name of the item/block. If you do F3+H you should be able to see a name bellow each item, that is the unique name that you need to use.

For the time being adding a meta number to the item doesn't work, this will get fixed in the next update.

**Comment by nylser** [comment]
Couldn't you also just add a command that takes the item that you're holding in your hand?

**Comment by AfterWind** [comment]
That's a good idea, I might do that as well.

**Comment by AfterWind** [comment]
Command for setting the cost item is close to impossible because of the way the config is constructed. But the issue with metadata not being accepted has been fixed and I've added a command to show you the item name you need to put in the config for the item you hold in hand. That's the best I could do.

**Comment by groveham** [comment]
That's pretty perfect to be honest! Thanks for the good work!
