### ISSUE TITLE
SORRY, really SORRY for asking...

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#130]
Hello, i am a server owner, and i will reopen my server on 01/04/2015, and i need to know if this AMAZING mod will have a new version until April.

Really sorry for asking, i know its boring, :/

**Comment by AfterWind** [comment]
Right, I did tell people that I am aiming to have a new alpha version out by the end of March. This is not 100% sure, since there are still LOTS of things to fix. The upside is that @krwminer started working on the new protection files and by the end of March he might have the basic protection out. If I don't find the time it might take 1-2 more weeks after the estimated release date.

Not a boring question, I like that people are actually wanting to use the software I have worked on.

Next time ask these types of question here please: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2212817-mytown-2-offers-protection-for-your-vanilla-and
