### ISSUE TITLE
PvP in town 

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#183]
I dont know if the flag does this, but, actually, the PvP flag only affects non residents.

For exemple. A stranger cant atack a resident, but, a resident can atack other resident.

I think it is better the PvP flag affect everyone...

**Comment by AfterWind** [comment]
I was not 100% sure whether to implement it like that or not. I mean, if a player comes to your town and tries to kill you or grief I think you should be able to kill him, although if it goes the other way around where you come to somebodies town and they kill you it might become an issue.

Also, if it's a pvp server and somebody comes to your town you should REALLY be able to kill him, he should not become invincible just by walking into a town. 

Those are the reasons why I implemented it that way. @evernife, your suggestion is OK simply because it is that way for many similar plugins. I will leave this open for further investigation.

**Comment by evernife** [comment]
If this is the point, try to make two flags

PvP
and
ResPvP(For exemple)

If its possible of course.

**Comment by AfterWind** [comment]
I could simply implement the current pvp protection into the "protectedEntities" flag and change the pvp flag so that it behaves like in MyTown1.

**Comment by evernife** [comment]
:D
