### ISSUE TITLE
[Request] General

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#203]
Would be more easy to do general requests....

1-->A way to teleport to a "t spawn" with an admin command (like /ta spawn NAME)
2-->A way to set  "t spawn" with an admin command (like /ta setspawn) (obviously shoud used in the town, so that there shoud be not a name for it.)
3-->A way to make PLOTS bigger than one CHUNK size.
4-->A way to sell plots/towns with a "sign", but, with "CostItem" ( I think this already exists, but i don't know how to do this, so, if exist, make a simple explanation to me please :D )

(I will be editing this one, i have had a few more suggestions, but i can't remember now :c)

**Comment by AfterWind** [comment]
Please do not make a general list of things since it's much easier to tell what the user wants from the tags and the issue's title and it's really difficult to discuss the issues individually. Sorry but I have to close this. :(

I know I have one, but that thing is just HUGE and many things might change but that's not only requests, it's mostly code stuffs.
