### ISSUE TITLE
Cannot change the maximum number of chunks a player can have

### ISSUE THREAD

**Issue by LameGirlyCurly** [MyEssentials/MyTown2#265]
Players complaining they have money but cannot claim more chunks. Configs don't show up anything that would limit the max claimable amount of chunks. With more players added to the town, the maximum limit goes up but not all players want residents.

Using currently 1.7.10-192-dev version.

**Comment by AfterWind** [comment]
`# The amount of maximum blocks a town gets from the mayor.
I:blocksMayor=5`

Simply set this to a high number and it will increase the maximum amount of claims per town.
Since only one mayor can be in a town at a time the increase will only occur once.
The formula of the limit for each town is: `blocksMayor` + `blocksResidents` * (noOfResidents - 1)

**Comment by JzJad** [comment]
I:blocksMayor=5
Basically changes the initial number of claims a town will get, not including the extra from each resident therefor after invited.
