### ISSUE TITLE
Crash :/

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#284]
http://pastebin.com/raw.php?i=931gdisF

using:
MyTown2-1.7.10-223-dev
MyEssentials-Core-1.7.10-50-dev
MyPermissions-1.7.10-13-dev

**Comment by FiveEYZ** [comment]
Derp, noticed i wasn't using latest MyEssentials-Core
will update and see if i get this random crash xD

**Comment by brunyman** [comment]
Hi, i'm getting this crash for a long time, from before the mod got into the beta stage, and still get it now using latest recommended version 0.1.3b. I'm using FTB Direwolf20 modpack on latest recommended version with cauldron KCauldron-1.7.10-1492.150

Crash 1:  http://pastebin.com/QsZEzT2U

Crash 2:  http://pastebin.com/eR26CSHH

Crash 3:  http://pastebin.com/Cy3YurZU

I made an older report about it, but the crash is still here with us :) , i get this crash about ~15 time a day, and it's the main server instability issue, i'm not sure what triggers it, it may be because a player disconnects in the login process but i don't know. Thanks

**Comment by FiveEYZ** [comment]
Gonna add that im not getting this crash anymore after updating myessentials-core to build 52.

Might as well add that im running it with FTB Infinity 1.10.1 and KCauldron-1.7.10-1448.133

**Comment by brunyman** [comment]
Ok, i'm going to test that essentials build too
