### ISSUE TITLE
Town select doesn't stay after reboot

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#375]
Basically what the subect says. I'm part of two towns, an Admin Town around spawn and my own Town around my base. I created the Admin town first, then my own personal town. I've done the command /t select PersonalTown but after every restart I need to re-do the command.
Is there a way for it to remember what option you've selected? Not a big bug as technically everything is working, except it remembering your preference.
Using MyTown2-1.7.10-0.3.1b.jar

**Comment by AfterWind** [comment]
Interesting, I have implemented this in the database. Probably missed loading it into memory when I did the refactoring.

**Comment by krwminer** [comment]
There are two problems:

1) The saveSelectedTown() never saves the DB entry because res.townsContainer.getMainTown() is never null, so it always tries to update instead of creating a new DB entry.
2) The loadSelectedTowns() does not work because it needs to called after loadResidentsToTowns(). (easy fix).

Open to suggestions on fixing problem 1 AfterWind.

**Comment by krwminer** [comment]
This is fixed. I will push it in on my next update.
