### ISSUE TITLE
Overcharging taxes

### ISSUE THREAD

**Issue by Callum-MM** [MyEssentials/MyTown2#380]
For some reason we have noticed that some towns are being charged double the rate that they should be being charged wheras most of the towns on the server are fine. Its just a couple that are being charged double but we really can't figure out why.

![image](https://cloud.githubusercontent.com/assets/14040343/10864126/73e4c68a-7fdb-11e5-87bb-e91d7b874936.png)

![image](https://cloud.githubusercontent.com/assets/14040343/10864127/77f62502-7fdb-11e5-923e-640dca1fb3de.png)

For the majority of towns, It costs them £20 per plot per day in upkeep but for this town, it costs £40 per plot per day for some reason. We checked to see if having two people in the town affected it but it doesn't

I've tried lots of recent versions and this bug appears to be happening in them all for the exact same towns.

**Comment by AfterWind** [comment]
This is because they have not paid their last upkeep.
`return (Config.instance.costTownUpkeep.get() + Config.instance.costAdditionalUpkeep.get() * town.townBlocksContainer.size()) * (1 + daysNotPaid);`

As you can see the amount is multiplied by 1 + `daysNotPaid` so, in your case it will translate to:
(0 + 20 * 11) * (1 + 1) = 440.

**Comment by Callum-MM** [comment]
Oh i see!!!!! Thats actually fantastic! Thanks a bunch!
