### ISSUE TITLE
Plots respect placeProtectionRange of the town they are in

### ISSUE THREAD

**Issue by afftor** [MyEssentials/MyTown2#396]
And won't let you to build on their borders.

**Comment by 0zlw** [comment]
Okay done some testing with Plots which was interesting.

Plots do indeed respect the placeProtectionRange in the same way as chunk borders work. This may be intended functionality? Otherwise maybe the config options could be split to allow customization.

One quirk of this is when placeProtectionRange=1, you can place two plots side by side to each other. This still applies so - you can't build on the border of your claim, and they can't on theirs (Which could also be intended functionality)

**Comment by afftor** [comment]
Does not really make any sense to me since when I select a plot I do intend to use all the size without additionally tweaking the config.

**Comment by Callum-MM** [comment]
Im having a similar issue and was hoping to share some more details. Place Protection Range applies to plots as well as to towns so if you have it set so that outsiders can't place blocks within 16 blocks of a town then it also means that your plots have to be 16 blocks apart if you are assigning owners otherwise each plot's protection range of 16 will overlap onto other plots. Basically unless your Protection range is 0 in the config file, you can't have plots right next to each other with different owners or PlotA will stop Player2 building in PlotB and PlotB will stop Player1 building in PlotA if you see what i mean. Maybe it would be possible to seperate Plot protection and Town protection ranges in the config so they become two settings rather than one?
