### ISSUE TITLE
Error with DIM 17

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#437]
All towns in "SurvivalII" world does not exist anymore, well, they exist in town list and database, but not in world. All of player houses are unprotected =/
If I try to type: /town spawn, my game and the server crashes, with this error: http://pastebin.com/9k9P4Q4y
So, I changed my town dimension in database and the /town spawn works, but if I try to type /town borders show, gives me a error message and this console error: http://pastebin.com/JqgJRzDs

**Comment by joserobjr** [comment]
My guess is that you are using a custom world created by a bukkit plugin and MT2 is mapping it by the dimension ID instead of the world name, and after a server reload the dimension ID changed so the old ID doesn't exists anymore. If I'm not wrong Bukkit worlds on cauldron servers have dynamic dimension ID only for compatibility with forge API and I think that there's a configuration somewhere to define a static value. I can be wrong through because I'm writing what I remember on top of my head.

**Comment by Esctogrillo** [comment]
I did not found anything else related with world ID in cauldron, kcauldron, spigot or bukkit.yml. So, I will change all SurvivalII town IDs from 17 to 20. I created a town in SurvivalII and the database informs that is dimension 20.

**Comment by Esctogrillo** [comment]
Ok, this not works.

**Comment by Esctogrillo** [comment]
Will works if I change all towns dimensions and their blocks.
